### ISSUE TITLE
Refseq genes in plotBedpe

### ISSUE THREAD

**Issue by rvidal404** [dphansti/Sushi#7]
Dear Author,

Thank you for developing this package. 
It is incredible to visualise some data.
However, I was wondering if it is possible to plot refseq genes below the x coordinates of the 
plotBedpe plot. I was thinking if calling layout() function would be only possible to achieve that. Do you know if there is a simpler way to do the same?

Thank you for your time,

Vidal

**Comment by dphansti** [comment]
I also typically use the layout function to combine plots.
